### ISSUE TITLE
Support for Grouping based on "output_dir" key

### ISSUE THREAD

**Issue by vishrutshah** [lmazuel/swagger-to-sdk#5]
We have a Ruby generator that takes care about the generating the sdk and it's wrapper top level folder. In that case, when we model the swagger_to_sdk_config.json's `projects` node as

```
...
    "azure_mgmt_datalake_analytics": {
      "swagger": "arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json",
      "autorest_options": {
        "Namespace": "Azure::ARM::DataLakeAnalytics::Catalog",
        "PackageName": "azure_mgmt_datalake_analytics_catalog"
      },
      "output_dir": "azure_mgmt_datalake_analytics/lib",
      "wrapper_filesOrDirs": [
        "azure_mgmt_datalake_analytics.rb"
      ]
    },
    "azure_mgmt_datalake_analytics": {
      "swagger": "arm-datalake-analytics/job/2016-03-20-preview/swagger/job.json",
      "autorest_options": {
        "Namespace": "Azure::ARM::DataLakeAnalytics::Job",
        "PackageName": "azure_mgmt_datalake_analytics_job"
      },
      "output_dir": "azure_mgmt_datalake_analytics/lib",
      "wrapper_filesOrDirs": [
        "azure_mgmt_datalake_analytics.rb"
      ]
    },
    "azure_mgmt_datalake_analytics": {
      "swagger": "arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json",
      "autorest_options": {
        "Namespace": "Azure::ARM::DataLakeAnalytics::Account",
        "PackageName": "azure_mgmt_datalake_analytics_account",
        "PackageVersion": "0.5.0"
      },
      "output_dir": "azure_mgmt_datalake_analytics/lib",
      "wrapper_filesOrDirs": [
        "azure_mgmt_datalake_analytics.rb"
      ]
    },
...
```

As Ruby code generator, takes care about creating sub folders (azure_mgmt_datalake_analytics_catalog, azure_mgmt_datalake_analytics_job, azure_mgmt_datalake_analytics_account), swagger-to-sdk should not delete the folders for each projects mentioned about before generating the code, otherwise it'll end up generating the code for only on project context and deleting the other two. 

We'd like to swagger-to-sdk tool's project context to understand output_dir group and delete things once for the grouped context and run generate three times in a raw to generate clients for each of three projects. 

Thanks,

**Comment by lmazuel** [comment]
It's complicated to automatically handle (risk on path semantically equivalent, but not written the same, wrapper_filesOrDirs repeated with no meaning, etc.), and anyway explicit is better than implicit (see [Zen of Python](https://www.python.org/dev/peps/pep-0020/) :))

What do you think about:
```
...
    "azure_mgmt_datalake_analytics": {
      "swaggers": [{
          "swagger": "arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json",
          "autorest_options": {
            "Namespace": "Azure::ARM::DataLakeAnalytics::Catalog",
            "PackageName": "azure_mgmt_datalake_analytics_catalog"
          }
      },{
          "swagger": "arm-datalake-analytics/job/2016-03-20-preview/swagger/job.json",
          "autorest_options": {
            "Namespace": "Azure::ARM::DataLakeAnalytics::Job",
            "PackageName": "azure_mgmt_datalake_analytics_job"
          }
      },{
          "swagger": "arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json",
          "autorest_options": {
            "Namespace": "Azure::ARM::DataLakeAnalytics::Account",
            "PackageName": "azure_mgmt_datalake_analytics_account",
            "PackageVersion": "0.5.0"
          }
      }],
      "output_dir": "azure_mgmt_datalake_analytics/lib",
      "wrapper_filesOrDirs": [
        "azure_mgmt_datalake_analytics.rb"
      ]
    },
...
```

**Comment by vishrutshah** [comment]
@lmazuel I like the new structure and it conveys the right explicit message that 

` project X` is generated from `swaggers list` of swagger files under `output_dir` with `wrapper_filesOrDirs` files untouched. 

This should perfectly work in our scenario.

**Comment by lmazuel** [comment]
Hi @vishrutshah 
Sorry for being so late on this. Now ADL is GA, how did you do for? Manually to workaround this?

**Comment by vishrutshah** [comment]
Actually, as Ruby team has prioritized ARM (Management) space SDKs over Data Plane for now, we did not have this issue as both [azure_mgmt_datalake_analytics](https://github.com/Azure/azure-sdk-for-ruby/blob/master/swagger_to_sdk_config.json#L93) & [azure_mgmt_datalake_store](https://github.com/Azure/azure-sdk-for-ruby/blob/master/swagger_to_sdk_config.json#L105) had only one management swagger spec i.e. `account.json`. So i did not face this issue in management space. 

But as we'll move forward with the generation of data plane where one sdk contain more than one swagger spec, we'll run into this. So i think we should support the feature as we get chance. 

What are your views?

**Comment by lmazuel** [comment]
Hi @vishrutshah news are... busy as hell.... But I don't forget it.

**Comment by lmazuel** [comment]
Will not be done, since conf is in Readme now.
