### ISSUE TITLE
New Tags needed to be added to the services under resources folder

### ISSUE THREAD

**Issue by sarangan12** [lmazuel/swagger-to-sdk#54]
The [resources](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager) folder in the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository has the following items combined in them:

- Policy
- Resources
- Links
- Locks
- Features
- Subscriptions
- Managed Applications

In SDKs such as [Python](https://github.com/Azure/azure-sdk-for-python) all the above items are combined to one unit and shipped. But, In SDKs such as [Ruby](https://github.com/Azure/azure-sdk-for-ruby) these items are shipped as individual gems such as azure_mgmt_policy, azure_mgmt_resources, etc. (Per discussion with @jhendrixMSFT, the [Go](https://github.com/Azure/azure-sdk-for-go) SDK also ship them as individual units)

In order to handle the above items, I have created (for Ruby) one [readme.ruby.md](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/readme.ruby.md) which has additional tags (in addition to the regular `ruby` and `multiapi` tags. The additional tags are listed below:

| No | Service                          | New Tag                      |
|-----|--------------------------|-------------------------|
|  1   | Policy                            | policy                          |
|  2   | Resources                     | resources                     |
|  3   | Links                             | links                              |
|  4   | Locks                            | locks                             |
|  5   | Features                        | features                        |
|  6   | Subscriptions                | subscriptions                |
|  7   | Managed Applications  | managedapplications  |

So, the swagger to sdk tool must be modified to handle these new tags. The modified logic should be something like: "If the modified files belong to the services listed in the table, then additional new tags must be added as listed in the table".

CC: @lmazuel @salameer

**Comment by lmazuel** [comment]
@sarangan12 can you duplicate it here:
https://github.com/Azure/swagger-to-sdk
