### ISSUE TITLE
Interested to use it for image-charts.com

### ISSUE THREAD

**Issue by FGRibreau** [lmazuel/swagger-to-sdk#7]
Hello !

First thing first, your tool seems awesome, we've dreamt about it!

At @imagecharts we use swagger to describe our API https://image-charts.com/swagger.json could you give us a little more explanation on how to use your tool? Should be have a monorepo with every language inside it? 

Do you have an example project that use swagger-to-sdk?

**Comment by lmazuel** [comment]
Hi @FGRibreau 

Thank you for your message :)
This is actually built for building Microsoft SDK cross-languages using [Autorest](https://github.com/Azure/autorest/). I guess this could be generalized to non-Autorest generator, adapting the launcher code (I doubt you use Autorest to generate your SDK?)
I have to move this repo into https://github.com/Azure/ first and add the MIT Licence.

Thanks!

**Comment by FGRibreau** [comment]
I see, thanks for the update, I think I'm first going to try swagger-generator and then start from there :)
