### ISSUE TITLE
Use npm autorest instead of Nuget download

### ISSUE THREAD

**Issue by lmazuel** [lmazuel/swagger-to-sdk#8]
Reference:
https://github.com/Azure/azure-rest-api-specs/pull/957

FYI @vishrutshah

**Comment by vishrutshah** [comment]
@lmazuel Just an FYI, It's not working on Ubuntu system yet due to some issues around dependencies in .NET Core.

**Comment by lmazuel** [comment]
@vishrutshah ouch, ok :/. So then I cannot use the latest Autorest in PR for now :/. Hope you'll fix that asap :)

**Comment by lmazuel** [comment]
Merged
